/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,ts,jsx,tsx,html,mdx}"],
  darkMode: "class",
  theme: {
    screens: {
      sm: '640px',   
      md: '768px',    
      lg: '1024px',   
      xl: '1280px',
      '2xl': '1536px'
    },
    extend: {
      colors: {
        // Primary colors
        primary: {
          background: "var(--primary-background)",
          foreground: "var(--primary-foreground)",
          accent: "var(--primary-accent)",
        },
        // Secondary colors
        secondary: {
          background: "var(--secondary-background)",
          foreground: "var(--secondary-foreground)",
          light: "var(--secondary-light)",
        },
        // Text colors
        text: {
          primary: "var(--text-primary)",
          secondary: "var(--text-secondary)",
          muted: "var(--text-muted)",
          link: "var(--text-link)",
          inverse: "var(--text-inverse)",
          translucent: "var(--text-translucent)",
        },
        // Background colors
        background: {
          main: "var(--bg-main)",
          dark: "var(--bg-dark)",
          card: "var(--bg-card)",
          modal: "var(--bg-modal)",
          overlay: "var(--bg-overlay)",
          'overlay-light': "var(--bg-overlay-light)",
          translucent: "var(--bg-translucent)",
        },
        // Border colors
        border: {
          primary: "var(--border-primary)",
          secondary: "var(--border-secondary)",
          light: "var(--border-light)",
        },
        // Component-specific colors - Button
        button: {
          'bg-primary': "var(--button-bg-primary)",
          'bg-secondary': "var(--button-bg-secondary)",
          'text-primary': "var(--button-text-primary)",
          'text-secondary': "var(--button-text-secondary)",
          'border-primary': "var(--button-border-primary)",
          'border-secondary': "var(--button-border-secondary)",
        },
        // Component-specific colors - Modal
        modal: {
          bg: "var(--modal-bg)",
          text: "var(--modal-text)",
          overlay: "var(--modal-overlay)",
        },
        // Component-specific colors - Footer
        footer: {
          bg: "var(--footer-bg)",
          text: "var(--footer-text)",
        },
      },
      // Typography
      fontSize: {
        'xs': 'var(--font-size-xs)',
        'sm': 'var(--font-size-sm)',
        'base': 'var(--font-size-base)',
        'md': 'var(--font-size-md)',
        'lg': 'var(--font-size-lg)',
        'xl': 'var(--font-size-xl)',
        '2xl': 'var(--font-size-2xl)',
        '3xl': 'var(--font-size-3xl)',
        '4xl': 'var(--font-size-4xl)',
        '5xl': 'var(--font-size-5xl)',
      },
      fontWeight: {
        'normal': 'var(--font-weight-normal)',
        'semibold': 'var(--font-weight-semibold)',
        'bold': 'var(--font-weight-bold)',
      },
      lineHeight: {
        'xs': 'var(--line-height-xs)',
        'sm': 'var(--line-height-sm)',
        'base': 'var(--line-height-base)',
        'md': 'var(--line-height-md)',
        'lg': 'var(--line-height-lg)',
        'xl': 'var(--line-height-xl)',
        '2xl': 'var(--line-height-2xl)',
        '3xl': 'var(--line-height-3xl)',
        '4xl': 'var(--line-height-4xl)',
        '5xl': 'var(--line-height-5xl)',
      },
      // Spacing
      spacing: {
        '1': 'var(--spacing-1)',
        '1.5': 'var(--spacing-1-5)',
        '2': 'var(--spacing-2)',
        '2.5': 'var(--spacing-2-5)',
        '3': 'var(--spacing-3)',
        '3.5': 'var(--spacing-3-5)',
        '4': 'var(--spacing-4)',
        '4.5': 'var(--spacing-4-5)',
        '5': 'var(--spacing-5)',
        '5.5': 'var(--spacing-5-5)',
        '6': 'var(--spacing-6)',
        '6.5': 'var(--spacing-6-5)',
        '7': 'var(--spacing-7)',
        '7.5': 'var(--spacing-7-5)',
        '8.5': 'var(--spacing-8-5)',
        '9': 'var(--spacing-9)',
        '10.5': 'var(--spacing-10-5)',
        '11.5': 'var(--spacing-11-5)',
        '12': 'var(--spacing-12)',
        '13': 'var(--spacing-13)',
        '14': 'var(--spacing-14)',
        '15': 'var(--spacing-15)',
        '16': 'var(--spacing-16)',
        '17': 'var(--spacing-17)',
        '21': 'var(--spacing-21)',
        '26.5': 'var(--spacing-26-5)',
        '27.5': 'var(--spacing-27-5)',
        '32.5': 'var(--spacing-32-5)',
        '34': 'var(--spacing-34)',
        '35.5': 'var(--spacing-35-5)',
        '38': 'var(--spacing-38)',
        '47.5': 'var(--spacing-47-5)',
        '56': 'var(--spacing-56)',
        '56.5': 'var(--spacing-56-5)',
        '61.5': 'var(--spacing-61-5)',
        '66.5': 'var(--spacing-66-5)',
      },
      padding: {
        '1': 'var(--padding-1)',
        '1.5': 'var(--padding-1-5)',
        '2.5': 'var(--padding-2-5)',
        '3': 'var(--padding-3)',
        '3.5': 'var(--padding-3-5)',
        '4': 'var(--padding-4)',
        '4.5': 'var(--padding-4-5)',
        '5': 'var(--padding-5)',
        '5.5': 'var(--padding-5-5)',
        '6.5': 'var(--padding-6-5)',
        '7': 'var(--padding-7)',
        '7.5': 'var(--padding-7-5)',
        '8': 'var(--padding-8)',
        '8.5': 'var(--padding-8-5)',
        '10': 'var(--padding-10)',
        '12.5': 'var(--padding-12-5)',
        '14': 'var(--padding-14)',
        '20': 'var(--padding-20)',
        '22.5': 'var(--padding-22-5)',
        '28': 'var(--padding-28)',
        '45': 'var(--padding-45)',
      },
      gap: {
        '0.5': 'var(--gap-0-5)',
        '1.5': 'var(--gap-1-5)',
        '2': 'var(--gap-2)',
        '2.5': 'var(--gap-2-5)',
        '3': 'var(--gap-3)',
        '3.5': 'var(--gap-3-5)',
        '4': 'var(--gap-4)',
        '5': 'var(--gap-5)',
        '5.5': 'var(--gap-5-5)',
        '6.5': 'var(--gap-6-5)',
        '7': 'var(--gap-7)',
        '7.5': 'var(--gap-7-5)',
        '8': 'var(--gap-8)',
        '8.5': 'var(--gap-8-5)',
        '9': 'var(--gap-9)',
        '9.5': 'var(--gap-9-5)',
        '10.5': 'var(--gap-10-5)',
        '14': 'var(--gap-14)',
        '14.5': 'var(--gap-14-5)',
        '15': 'var(--gap-15)',
        '16': 'var(--gap-16)',
        '16.5': 'var(--gap-16-5)',
        '17': 'var(--gap-17)',
        '18': 'var(--gap-18)',
        '21.5': 'var(--gap-21-5)',
        '29.5': 'var(--gap-29-5)',
        '30.5': 'var(--gap-30-5)',
      },
      // Border Radius
      borderRadius: {
        'xs': 'var(--radius-xs)',
        'sm': 'var(--radius-sm)',
        'md': 'var(--radius-md)',
        'lg': 'var(--radius-lg)',
        'xl': 'var(--radius-xl)',
        '2xl': 'var(--radius-2xl)',
        'full': 'var(--radius-full)',
      },
      // Border Width
      borderWidth: {
        'thin': 'var(--border-thin)',
        'medium': 'var(--border-medium)',
        'thick': 'var(--border-thick)',
      },
      // Layout
      width: {
        'icon-sm': 'var(--width-icon-sm)',
        'icon-md': 'var(--width-icon-md)',
        'button-sm': 'var(--width-button-sm)',
        'button-md': 'var(--width-button-md)',
        'button-lg': 'var(--width-button-lg)',
        'card-sm': 'var(--width-card-sm)',
        'card-md': 'var(--width-card-md)',
        'card-lg': 'var(--width-card-lg)',
        'card-xl': 'var(--width-card-xl)',
      },
    },
  },
  plugins: [],
};